# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zongheyanshi.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import zhysRC
class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(1138, 648)
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(10, 0, 541, 491))
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(dialog)
        self.pushButton.setGeometry(QtCore.QRect(20, 500, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 500, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 500, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(dialog)
        self.label_2.setGeometry(QtCore.QRect(560, 100, 571, 81))
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(dialog)
        self.label_3.setGeometry(QtCore.QRect(560, 10, 571, 81))
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(dialog)
        self.label_4.setGeometry(QtCore.QRect(560, 250, 571, 171))
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton_4 = QtWidgets.QPushButton(dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(640, 510, 51, 51))
        self.pushButton_4.setStyleSheet("border-image: url(:/globes_write.png);")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(645, 489, 41, 21))
        self.pushButton_5.setStyleSheet("border-image: url(:/shang.png);\n"
"")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(646, 560, 41, 21))
        self.pushButton_6.setStyleSheet("border-image: url(:/xia.png);")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(692, 514, 21, 41))
        self.pushButton_7.setStyleSheet("border-image: url(:/you.png);")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(619, 514, 21, 41))
        self.pushButton_8.setStyleSheet("border-image: url(:/zuo.png);")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(624, 460, 81, 21))
        self.pushButton_9.setStyleSheet("border-image: url(:/shangjia.png);")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(dialog)
        self.pushButton_10.setGeometry(QtCore.QRect(627, 587, 81, 21))
        self.pushButton_10.setStyleSheet("border-image: url(:/xiajia.png);")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(dialog)
        self.pushButton_11.setGeometry(QtCore.QRect(720, 500, 21, 71))
        self.pushButton_11.setStyleSheet("border-image: url(:/youjia.png);")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(dialog)
        self.pushButton_12.setGeometry(QtCore.QRect(590, 500, 21, 71))
        self.pushButton_12.setStyleSheet("border-image: url(:/zuojia.png);")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.comboBox = QtWidgets.QComboBox(dialog)
        self.comboBox.setGeometry(QtCore.QRect(849, 460, 81, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(dialog)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(780, 460, 51, 21))
        self.lineEdit.setFrame(False)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(dialog)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QtCore.QRect(782, 490, 51, 21))
        self.lineEdit_2.setFrame(False)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(dialog)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setGeometry(QtCore.QRect(782, 520, 51, 21))
        self.lineEdit_3.setFrame(False)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(dialog)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setGeometry(QtCore.QRect(785, 550, 51, 21))
        self.lineEdit_4.setFrame(False)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.comboBox_2 = QtWidgets.QComboBox(dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(850, 550, 81, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.pushButton_13 = QtWidgets.QPushButton(dialog)
        self.pushButton_13.setGeometry(QtCore.QRect(783, 580, 71, 28))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(dialog)
        self.pushButton_14.setGeometry(QtCore.QRect(863, 580, 70, 28))
        self.pushButton_14.setObjectName("pushButton_14")
        self.lineEdit_5 = QtWidgets.QLineEdit(dialog)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setGeometry(QtCore.QRect(583, 622, 51, 21))
        self.lineEdit_5.setFrame(False)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.radioButton = QtWidgets.QRadioButton(dialog)
        self.radioButton.setGeometry(QtCore.QRect(631, 622, 115, 19))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(701, 622, 115, 19))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(dialog)
        self.radioButton_3.setGeometry(QtCore.QRect(771, 622, 115, 19))
        self.radioButton_3.setObjectName("radioButton_3")
        self.lineEdit_6 = QtWidgets.QLineEdit(dialog)
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setGeometry(QtCore.QRect(560, 436, 71, 21))
        self.lineEdit_6.setFrame(False)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.textBrowser = QtWidgets.QTextBrowser(dialog)
        self.textBrowser.setGeometry(QtCore.QRect(950, 440, 181, 201))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_15 = QtWidgets.QPushButton(dialog)
        self.pushButton_15.setGeometry(QtCore.QRect(906, 520, 21, 21))
        self.pushButton_15.setStyleSheet("border-image: url(:/you.png);")
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(dialog)
        self.pushButton_16.setGeometry(QtCore.QRect(854, 519, 21, 21))
        self.pushButton_16.setStyleSheet("border-image: url(:/zuo.png);")
        self.pushButton_16.setText("")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(dialog)
        self.pushButton_17.setGeometry(QtCore.QRect(875, 515, 31, 31))
        self.pushButton_17.setStyleSheet("border-image: url(:/globes_write.png);")
        self.pushButton_17.setText("")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(dialog)
        self.pushButton_18.setGeometry(QtCore.QRect(874, 485, 31, 31))
        self.pushButton_18.setStyleSheet("border-image: url(:/globes_write.png);")
        self.pushButton_18.setText("")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(dialog)
        self.pushButton_19.setGeometry(QtCore.QRect(853, 489, 21, 21))
        self.pushButton_19.setStyleSheet("border-image: url(:/zuo.png);")
        self.pushButton_19.setText("")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(dialog)
        self.pushButton_20.setGeometry(QtCore.QRect(905, 490, 21, 21))
        self.pushButton_20.setStyleSheet("border-image: url(:/you.png);")
        self.pushButton_20.setText("")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(dialog)
        self.pushButton_21.setGeometry(QtCore.QRect(250, 560, 93, 28))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(dialog)
        self.pushButton_22.setGeometry(QtCore.QRect(560, 190, 93, 28))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(dialog)
        self.pushButton_23.setGeometry(QtCore.QRect(660, 190, 93, 28))
        self.pushButton_23.setObjectName("pushButton_23")
        self.lineEdit_7 = QtWidgets.QLineEdit(dialog)
        self.lineEdit_7.setEnabled(False)
        self.lineEdit_7.setGeometry(QtCore.QRect(560, 228, 71, 21))
        self.lineEdit_7.setFrame(False)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")

        self.retranslateUi(dialog)
        self.pushButton.clicked.connect(dialog.bOpenCap)
        self.pushButton_2.clicked.connect(dialog.bObjectDetect)
        self.pushButton_3.clicked.connect(dialog.bSaveCapImg)
        self.pushButton_21.clicked.connect(dialog.bExit)
        self.pushButton_22.clicked.connect(dialog.bOpenAudio)
        self.pushButton_23.clicked.connect(dialog.bCloseAudio)
        self.pushButton_12.clicked.connect(dialog.bYTLeftPlus)
        self.pushButton_8.clicked.connect(dialog.bYTLeft)
        self.pushButton_4.clicked.connect(dialog.bYTReset)
        self.pushButton_5.clicked.connect(dialog.bYTUp)
        self.pushButton_9.clicked.connect(dialog.bYTUpPlus)
        self.pushButton_7.clicked.connect(dialog.bYTRight)
        self.pushButton_11.clicked.connect(dialog.bYTRightPlus)
        self.pushButton_6.clicked.connect(dialog.bYTDown)
        self.pushButton_10.clicked.connect(dialog.bYTDownPlus)
        self.comboBox.currentIndexChanged['int'].connect(dialog.cYTVelChange)
        self.comboBox_2.currentIndexChanged['QString'].connect(dialog.cYTComChange)
        self.pushButton_19.clicked.connect(dialog.bYTRollLeft)
        self.pushButton_18.clicked.connect(dialog.bYTRollReset)
        self.pushButton_20.clicked.connect(dialog.bYTRollRight)
        self.pushButton_16.clicked.connect(dialog.bYTFocusLeft)
        self.pushButton_17.clicked.connect(dialog.bYTFocusReset)
        self.pushButton_15.clicked.connect(dialog.bYTFocusRight)
        self.pushButton_13.clicked.connect(dialog.bOpenCom)
        self.pushButton_14.clicked.connect(dialog.bCloseCom)
        self.radioButton.toggled['bool'].connect(dialog.rYTMode1)
        self.radioButton_2.toggled['bool'].connect(dialog.rYTMode2)
        self.radioButton_3.toggled['bool'].connect(dialog.rYTMode3)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "综合演示"))
        self.pushButton.setText(_translate("dialog", "打开视频"))
        self.pushButton_2.setText(_translate("dialog", "目标检测"))
        self.pushButton_3.setText(_translate("dialog", "存储"))
        self.comboBox.setItemText(0, _translate("dialog", "1"))
        self.comboBox.setItemText(1, _translate("dialog", "2"))
        self.comboBox.setItemText(2, _translate("dialog", "3"))
        self.comboBox.setItemText(3, _translate("dialog", "4"))
        self.comboBox.setItemText(4, _translate("dialog", "5"))
        self.lineEdit.setText(_translate("dialog", "速度："))
        self.lineEdit_2.setText(_translate("dialog", "横滚"))
        self.lineEdit_3.setText(_translate("dialog", "焦距"))
        self.lineEdit_4.setText(_translate("dialog", "端口："))
        self.comboBox_2.setItemText(0, _translate("dialog", "com1"))
        self.comboBox_2.setItemText(1, _translate("dialog", "com2"))
        self.comboBox_2.setItemText(2, _translate("dialog", "com3"))
        self.comboBox_2.setItemText(3, _translate("dialog", "com4"))
        self.comboBox_2.setItemText(4, _translate("dialog", "com5"))
        self.comboBox_2.setItemText(5, _translate("dialog", "com6"))
        self.comboBox_2.setItemText(6, _translate("dialog", "com7"))
        self.comboBox_2.setItemText(7, _translate("dialog", "com8"))
        self.pushButton_13.setText(_translate("dialog", "打开端口"))
        self.pushButton_14.setText(_translate("dialog", "关闭端口"))
        self.lineEdit_5.setText(_translate("dialog", "模式："))
        self.radioButton.setText(_translate("dialog", "模式1"))
        self.radioButton_2.setText(_translate("dialog", "模式2"))
        self.radioButton_3.setText(_translate("dialog", "模式3"))
        self.lineEdit_6.setText(_translate("dialog", "云台控制"))
        self.pushButton_21.setText(_translate("dialog", "退出"))
        self.pushButton_22.setText(_translate("dialog", "打开声频"))
        self.pushButton_23.setText(_translate("dialog", "关闭声频"))
        self.lineEdit_7.setText(_translate("dialog", "定向"))


